name: Java CI

on:
  push:
    branches: [ main, feature/*, refactor/* fix/* ]
  pull_request:
    branches: [ main, feature/*, refactor/* fix/* ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-gradle
      - name: Build and test with Gradle
        run: ./gradlew test