name: Java CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'Goldmensch/jtemplate' && github.ref_name != 'master'}}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-gradle
      - name: Build and test with Gradle
        run: ./gradlew test