name: Setup Repository
on:
  workflow_dispatch:
    inputs:
      project_name:
        description: the project's name, used in gradle
        required: true
        type: string
      project_description:
        description: the project's description
        required: true
        type: string
      java_version:
        description: the java version
        required: true
        type: number
      author_name:
        description: the author's name
        type: string
        required: true
      license:
        description: the project's license
        type: choice
        required: true
        options:
          - GPL-2.0
          - GPL-3.0
          - AFL-3.0
          - MIT
          - Apache-2.0
          - AGPL-3.0
          - LGPL-2.1
          - LGPL-3.0
          - Artistic-2.0
          - BSL-1.0
          - BSD-2-Clause
          - BSD-3-Clause
          - BSD-3-Clause-Clear
          - BSD-4-Clause
          - 0BSD
          - CC
          - CC0-1.0
          - CC-BY-4.0
          - CC-BY-SA-4.0
          - WTFPL
          - ECL-2.0
          - EPL-1.0
          - EUPL-1.1
          - ISC
          - LPPL-1.3c
          - MS-PL
          - MPL-2.0
          - OSL-3.0
          - PostgreSQL
          - OFL-1.1
          - NCSA
          - Unlicense
          - Zlib


jobs:
  replace_placeholder:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jbang
        uses: jbangdev/jbang-action@v0.126.3
        with:
          script: ./.github/workflows/setup-repo/ReplacePlaceholder.java
        env:
          PROJECT_NAME: ${{ inputs.project_name }}
          PROJECT_DESC: ${{ inputs.project_description }}
          JAVA_VERSION: ${{ inputs.java_version }}
          AUTHOR_NAME: ${{ inputs.author_name }}
          LICENSE_NAME: ${{ inputs.license }}
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "Prepare repository"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
  gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4